{{ config(
    materialized='incremental',
    incremental_strategy='append',
    schema='landing'
) }}

{#-- Reads the raw AEMO daily files the existing pipeline already landed (Files/csv/daily/*),
     filtering to the DREGION price records. append (not merge): the WHERE filters to files
     NOT already in {{ this }}, so dedup is done in SQL — a key-join merge would be redundant
     work that scans the target. The duckrun original used 'safeappend' (DuckDB compare-and-
     swap); Fabric has no such thing, but the file-level NOT IN filter keeps the append
     idempotent at file grain. No partition_by — Fabric Warehouse has no table partitioning;
     month_key is kept as a plain column. --#}

{%- set read_cols = [
  'I','UNIT','XX','VERSION','SETTLEMENTDATE','RUNNO','REGIONID','INTERVENTION','RRP','EEP',
  'ROP','APCFLAG','MARKETSUSPENDEDFLAG','TOTALDEMAND','DEMANDFORECAST','DISPATCHABLEGENERATION',
  'DISPATCHABLELOAD','NETINTERCHANGE','EXCESSGENERATION','LOWER5MINDISPATCH','LOWER5MINIMPORT',
  'LOWER5MINLOCALDISPATCH','LOWER5MINLOCALPRICE','LOWER5MINLOCALREQ','LOWER5MINPRICE','LOWER5MINREQ',
  'LOWER5MINSUPPLYPRICE','LOWER60SECDISPATCH','LOWER60SECIMPORT','LOWER60SECLOCALDISPATCH',
  'LOWER60SECLOCALPRICE','LOWER60SECLOCALREQ','LOWER60SECPRICE','LOWER60SECREQ','LOWER60SECSUPPLYPRICE',
  'LOWER6SECDISPATCH','LOWER6SECIMPORT','LOWER6SECLOCALDISPATCH','LOWER6SECLOCALPRICE','LOWER6SECLOCALREQ',
  'LOWER6SECPRICE','LOWER6SECREQ','LOWER6SECSUPPLYPRICE','RAISE5MINDISPATCH','RAISE5MINIMPORT',
  'RAISE5MINLOCALDISPATCH','RAISE5MINLOCALPRICE','RAISE5MINLOCALREQ','RAISE5MINPRICE','RAISE5MINREQ',
  'RAISE5MINSUPPLYPRICE','RAISE60SECDISPATCH','RAISE60SECIMPORT','RAISE60SECLOCALDISPATCH',
  'RAISE60SECLOCALPRICE','RAISE60SECLOCALREQ','RAISE60SECPRICE','RAISE60SECREQ','RAISE60SECSUPPLYPRICE',
  'RAISE6SECDISPATCH','RAISE6SECIMPORT','RAISE6SECLOCALDISPATCH','RAISE6SECLOCALPRICE','RAISE6SECLOCALREQ',
  'RAISE6SECPRICE','RAISE6SECREQ','RAISE6SECSUPPLYPRICE','AGGREGATEDISPATCHERROR','AVAILABLEGENERATION',
  'AVAILABLELOAD','INITIALSUPPLY','CLEAREDSUPPLY','LOWERREGIMPORT','LOWERREGLOCALDISPATCH',
  'LOWERREGLOCALREQ','LOWERREGREQ','RAISEREGIMPORT','RAISEREGLOCALDISPATCH','RAISEREGLOCALREQ',
  'RAISEREGREQ','RAISE5MINLOCALVIOLATION','RAISEREGLOCALVIOLATION','RAISE60SECLOCALVIOLATION',
  'RAISE6SECLOCALVIOLATION','LOWER5MINLOCALVIOLATION','LOWERREGLOCALVIOLATION','LOWER60SECLOCALVIOLATION',
  'LOWER6SECLOCALVIOLATION','RAISE5MINVIOLATION','RAISEREGVIOLATION','RAISE60SECVIOLATION',
  'RAISE6SECVIOLATION','LOWER5MINVIOLATION','LOWERREGVIOLATION','LOWER60SECVIOLATION','LOWER6SECVIOLATION',
  'RAISE6SECRRP','RAISE6SECROP','RAISE6SECAPCFLAG','RAISE60SECRRP','RAISE60SECROP','RAISE60SECAPCFLAG',
  'RAISE5MINRRP','RAISE5MINROP','RAISE5MINAPCFLAG','RAISEREGRRP','RAISEREGROP','RAISEREGAPCFLAG',
  'LOWER6SECRRP','LOWER6SECROP','LOWER6SECAPCFLAG','LOWER60SECRRP','LOWER60SECROP','LOWER60SECAPCFLAG',
  'LOWER5MINRRP','LOWER5MINROP','LOWER5MINAPCFLAG','LOWERREGRRP','LOWERREGROP','LOWERREGAPCFLAG',
  'RAISE6SECACTUALAVAILABILITY','RAISE60SECACTUALAVAILABILITY','RAISE5MINACTUALAVAILABILITY',
  'RAISEREGACTUALAVAILABILITY','LOWER6SECACTUALAVAILABILITY','LOWER60SECACTUALAVAILABILITY',
  'LOWER5MINACTUALAVAILABILITY','LOWERREGACTUALAVAILABILITY','LORSURPLUS','LRCSURPLUS'
] -%}
{%- set num_cols = read_cols | reject('in', ['I','UNIT','XX','REGIONID','SETTLEMENTDATE']) | list -%}

SELECT
  [UNIT],
  [REGIONID],
  {{ cast_floats(num_cols) }}
  {{ parse_filename('src.filepath(1)') }} AS [file],
  TRY_CAST([SETTLEMENTDATE] AS DATETIME2(6)) AS [SETTLEMENTDATE],
  TRY_CAST([SETTLEMENTDATE] AS DATE) AS [DATE],
  YEAR(TRY_CAST([SETTLEMENTDATE] AS DATETIME2(6))) AS [YEAR],
  -- Monthly partition key (YYYYMM): low-cardinality column kept for downstream pruning
  -- (Fabric has no native partitioning, but the column is still useful as a filter).
  YEAR(TRY_CAST([SETTLEMENTDATE] AS DATETIME2(6))) * 100
    + MONTH(TRY_CAST([SETTLEMENTDATE] AS DATETIME2(6))) AS [month_key]
FROM {{ openrowset_csv(get_csv_archive_path() ~ '/daily/*', read_cols) }} AS src
WHERE [I] = 'D' AND [UNIT] = 'DREGION' AND [VERSION] = '3'
{%- if is_incremental() %}
  AND {{ parse_filename('src.filepath(1)') }} NOT IN (SELECT DISTINCT [file] FROM {{ this }})
{%- endif %}
